### ISSUE TITLE
Panic on Linux system

### ISSUE THREAD

**Issue by MateuSai** [mtkennerly/ludusavi#406]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Standalone

### Description

When I try to execute the program I get:

```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5993c00cca55 - <unknown>
   1:     0x5993c00fc27b - <unknown>
   2:     0x5993c00c845f - <unknown>
   3:     0x5993c00cc82e - <unknown>
   4:     0x5993c00cdd79 - <unknown>
   5:     0x5993c00cdb1a - <unknown>
   6:     0x5993c00ce213 - <unknown>
   7:     0x5993c00ce0f4 - <unknown>
   8:     0x5993c00ccf19 - <unknown>
   9:     0x5993c00cde27 - <unknown>
  10:     0x5993bef5c6a3 - <unknown>
  11:     0x5993bef5cb96 - <unknown>
  12:     0x5993bfa8901a - <unknown>
  13:     0x5993bfa5d55e - <unknown>
  14:     0x5993bf16a214 - <unknown>
  15:     0x5993bf150458 - <unknown>
  16:     0x5993bf304849 - <unknown>
  17:     0x5993bf13f5bb - <unknown>
  18:     0x5993bf178cbc - <unknown>
  19:     0x5993bf05e796 - <unknown>
  20:     0x5993bf2c60d3 - <unknown>
  21:     0x5993bf14e8e9 - <unknown>
  22:     0x5993c00be04d - <unknown>
  23:     0x5993bf05f1d5 - <unknown>
  24:     0x75a8a1c29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25:     0x75a8a1c29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  26:     0x5993bef5d21e - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:227:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    48421 IOT instruction (core dumped)  ./ludusavi
```

I also tried downloading from cargo and flathub, bith versions crash too.

My system specs are:

OS: Pop!_OS 22.04 LTS x86_64
DE: Plasma 5.24.7
WM: KWin
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M

### Logs

Excuting with ´RUST_LOG=ludusavi=debug´ I get the same output as mentioned above:

```
[~/Downloads]$ RUST_LOG=ludusavi=debug ./ludusavi 
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x56c137fd5a55 - <unknown>
   1:     0x56c13800527b - <unknown>
   2:     0x56c137fd145f - <unknown>
   3:     0x56c137fd582e - <unknown>
   4:     0x56c137fd6d79 - <unknown>
   5:     0x56c137fd6b1a - <unknown>
   6:     0x56c137fd7213 - <unknown>
   7:     0x56c137fd70f4 - <unknown>
   8:     0x56c137fd5f19 - <unknown>
   9:     0x56c137fd6e27 - <unknown>
  10:     0x56c136e656a3 - <unknown>
  11:     0x56c136e65b96 - <unknown>
  12:     0x56c13799201a - <unknown>
  13:     0x56c13796655e - <unknown>
  14:     0x56c137073214 - <unknown>
  15:     0x56c137059458 - <unknown>
  16:     0x56c13720d849 - <unknown>
  17:     0x56c1370485bb - <unknown>
  18:     0x56c137081cbc - <unknown>
  19:     0x56c136f67796 - <unknown>
  20:     0x56c1371cf0d3 - <unknown>
  21:     0x56c1370578e9 - <unknown>
  22:     0x56c137fc704d - <unknown>
  23:     0x56c136f681d5 - <unknown>
  24:     0x71c0b8a29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25:     0x71c0b8a29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  26:     0x56c136e6621e - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:227:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    50328 IOT instruction (core dumped)  RUST_LOG=ludusavi=debug ./ludusavi
```

The output using `RUST_BACKTRACE=full` is as follows:

```
[0.429s][134][~/Downloads]$ RUST_BACKTRACE=full ludusavi 
thread 'main' panicked at /home/mateus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
stack backtrace:
   0:     0x5cb7fdae9306 - <unknown>
   1:     0x5cb7fdb1b030 - <unknown>
   2:     0x5cb7fdae516f - <unknown>
   3:     0x5cb7fdae90e4 - <unknown>
   4:     0x5cb7fdaea967 - <unknown>
   5:     0x5cb7fdaea6c9 - <unknown>
   6:     0x5cb7fdaeadf8 - <unknown>
   7:     0x5cb7fdaeacd2 - <unknown>
   8:     0x5cb7fdae9806 - <unknown>
   9:     0x5cb7fdaeaa30 - <unknown>
  10:     0x5cb7fc956e05 - <unknown>
  11:     0x5cb7fc957353 - <unknown>
  12:     0x5cb7fcd7f744 - <unknown>
  13:     0x5cb7fcd574c5 - <unknown>
  14:     0x5cb7fcab11b3 - <unknown>
  15:     0x5cb7fcd4a4d5 - <unknown>
  16:     0x5cb7fca88d0a - <unknown>
  17:     0x5cb7fcac4656 - <unknown>
  18:     0x5cb7fccc0963 - <unknown>
  19:     0x5cb7fcc5b2d9 - <unknown>
  20:     0x5cb7fdadaaa1 - <unknown>
  21:     0x5cb7fcac4aa5 - <unknown>
  22:     0x75d904629d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23:     0x75d904629e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  24:     0x5cb7fc9578f5 - <unknown>
  25:                0x0 - <unknown>
thread 'main' panicked at /home/mateus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5cb7fdae9306 - <unknown>
   1:     0x5cb7fdb1b030 - <unknown>
   2:     0x5cb7fdae516f - <unknown>
   3:     0x5cb7fdae90e4 - <unknown>
   4:     0x5cb7fdaea967 - <unknown>
   5:     0x5cb7fdaea6c9 - <unknown>
   6:     0x5cb7fdaeadf8 - <unknown>
   7:     0x5cb7fdaeacd2 - <unknown>
   8:     0x5cb7fdae9806 - <unknown>
   9:     0x5cb7fdaeaa30 - <unknown>
  10:     0x5cb7fc956e05 - <unknown>
  11:     0x5cb7fc957353 - <unknown>
  12:     0x5cb7fd499e73 - <unknown>
  13:     0x5cb7fd4a65c5 - <unknown>
  14:     0x5cb7fcab06a4 - <unknown>
  15:     0x5cb7fcd578b3 - <unknown>
  16:     0x5cb7fcab11b3 - <unknown>
  17:     0x5cb7fcd4a4d5 - <unknown>
  18:     0x5cb7fca88d0a - <unknown>
  19:     0x5cb7fcac4656 - <unknown>
  20:     0x5cb7fccc0963 - <unknown>
  21:     0x5cb7fcc5b2d9 - <unknown>
  22:     0x5cb7fdadaaa1 - <unknown>
  23:     0x5cb7fcac4aa5 - <unknown>
  24:     0x75d904629d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25:     0x75d904629e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  26:     0x5cb7fc9578f5 - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:163:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    50970 IOT instruction (core dumped)  RUST_BACKTRACE=full ludusavi

```

The contents of my log file are:

```
[2024-10-15T07:55:49.681Z] DEBUG [ludusavi] Version: 0.25.0
[2024-10-15T07:55:49.700Z] DEBUG [ludusavi::gui::app] Config on startup: Config { runtime: Runtime { threads: None }, release: Release { check: true }, manifest: ManifestConfig { url: None, enable: true, secondary: [] }, language: English, theme: Light, roots: [Steam(Steam { path: StrictPath { raw: "/home/mateus/.steam/debian-installation", basis: None } }), Gog(Gog { path: StrictPath { raw: "/home/mateus/GOG Games", basis: None } }), Heroic(Heroic { path: StrictPath { raw: "/home/mateus/.var/app/com.heroicgameslauncher.hgl/config/heroic", basis: None } }), Lutris(Lutris { path: StrictPath { raw: "/home/mateus/.config/lutris", basis: None }, database: Some(StrictPath { raw: "/home/mateus/.local/share/lutris/pga.db", basis: None }) })], redirects: [], backup: BackupConfig { path: StrictPath { raw: "/home/mateus/ludusavi-backup", basis: None }, ignored_games: {}, filter: BackupFilter { exclude_store_screenshots: false, cloud: CloudFilter { exclude: false, epic: false, gog: false, origin: false, steam: false, uplay: false }, ignored_paths: [], ignored_registry: [] }, toggled_paths: ToggledPaths({}), toggled_registry: ToggledRegistry({}), sort: Sort { key: Status, reversed: false }, retention: Retention { full: 1, differential: 0, force_new_full: false }, format: BackupFormats { chosen: Simple, zip: ZipConfig { compression: Deflate }, compression: Compression { deflate: DeflateCompression { level: 6 }, bzip2: Bzip2Compression { level: 6 }, zstd: ZstdCompression { level: 10 } } } }, restore: RestoreConfig { path: StrictPath { raw: "/home/mateus/ludusavi-backup", basis: None }, ignored_games: {}, toggled_paths: ToggledPaths({}), toggled_registry: ToggledRegistry({}), sort: Sort { key: Status, reversed: false } }, scan: Scan { show_deselected_games: true, show_unchanged_games: true, show_unscanned_games: true }, cloud: Cloud { remote: None, path: "ludusavi-backup", synchronize: true }, apps: Apps { rclone: App { path: StrictPath { raw: "/usr/bin/rclone", basis: None }, arguments: "--fast-list --ignore-checksum" } }, custom_games: [] }
```

**Comment by mtkennerly** [comment]
Hi! Thanks for the detailed report. Graphics-related issues can be tricky, but here are a few options:

* Could you try this build and see if it works any better? This is the latest development version: [ludusavi-v0.25.0-post.27+261a9f6-linux.tar.gz](https://github.com/user-attachments/files/17380991/ludusavi-v0.25.0-post.27%2B261a9f6-linux.tar.gz)
* Does it help if you set `ICED_BACKEND=tiny-skia` in your environment variables?

**Comment by MateuSai** [comment]
It worked with `ICED_BACKEND=tiny-skia`, thank you very much for the help and for making this amazing program.

**Comment by mtkennerly** [comment]
No problem :D I'm glad that helped.

**Comment by TheBossMagnus** [comment]
> Hi! Thanks for the detailed report. Graphics-related issues can be tricky, but here are a few options:
> 
>     * Could you try this build and see if it works any better? This is the latest development version: [ludusavi-v0.25.0-post.27+261a9f6-linux.tar.gz](https://github.com/user-attachments/files/17380991/ludusavi-v0.25.0-post.27%2B261a9f6-linux.tar.gz)
> 
>     * Does it help if you set `ICED_BACKEND=tiny-skia` in your environment variables?

I'm having a similar crash, and ICED_BACKEND=tiny-skia fixes it. using 26.0. Shall i open a new issue?

**Comment by mtkennerly** [comment]
> I'm having a similar crash, and ICED_BACKEND=tiny-skia fixes it. using 26.0. Shall i open a new issue?

No need for a new ticket. These kinds of issues are very system/driver-dependent, so unfortunately there's not much to do besides using the environment variable 😅
